/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccessScope :
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum AccessScope {
    #[serde(rename = "AccessScope")]
    AccessScope {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
    #[serde(rename = "GlobalScope")]
    GlobalScope {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
    #[serde(rename = "OrganizationScope")]
    OrganizationScope {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
    #[serde(rename = "ProjectScope")]
    ProjectScope {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
}

impl Default for AccessScope {
    fn default() -> Self {
        Self::AccessScope {
            id: Default::default(),
        }
    }
}
