/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActivityItem :
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum ActivityItem {
    #[serde(rename = "ActivityItem")]
    ActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "AttachmentActivityItem")]
    AttachmentActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "CommentActivityItem")]
    CommentActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "CommentAttachmentsActivityItem")]
    CommentAttachmentsActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "CreatedDeletedActivityItem")]
    CreatedDeletedActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "CustomFieldActivityItem")]
    CustomFieldActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "IssueCreatedActivityItem")]
    IssueCreatedActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "IssueResolvedActivityItem")]
    IssueResolvedActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "LinksActivityItem")]
    LinksActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "MultiValueActivityItem")]
    MultiValueActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "ProjectActivityItem")]
    ProjectActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "SimpleValueActivityItem")]
    SimpleValueActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "SingleValueActivityItem")]
    SingleValueActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "SprintActivityItem")]
    SprintActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "TagsActivityItem")]
    TagsActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "TextCustomFieldActivityItem")]
    TextCustomFieldActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "TextMarkupActivityItem")]
    TextMarkupActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "UsesMarkupActivityItem")]
    UsesMarkupActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "VcsChangeActivityItem")]
    VcsChangeActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "VisibilityActivityItem")]
    VisibilityActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "VisibilityGroupActivityItem")]
    VisibilityGroupActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "VisibilityUserActivityItem")]
    VisibilityUserActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "VotersActivityItem")]
    VotersActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "WorkItemActivityItem")]
    WorkItemActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "WorkItemAuthorActivityItem")]
    WorkItemAuthorActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "WorkItemDurationActivityItem")]
    WorkItemDurationActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
    #[serde(rename = "WorkItemTypeActivityItem")]
    WorkItemTypeActivityItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
        added: Option<serde_json::Value>,
        #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
        author: Option<Box<models::User>>,
        #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
        category: Option<Box<models::ActivityCategory>>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::FilterField>>,
        #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
        removed: Option<serde_json::Value>,
        #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
        target: Option<serde_json::Value>,
        #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
        target_member: Option<String>,
        #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
        timestamp: Option<i64>,
    },
}

impl Default for ActivityItem {
    fn default() -> Self {
        Self::ActivityItem {
            id: Default::default(),
            added: Default::default(),
            author: Default::default(),
            category: Default::default(),
            field: Default::default(),
            removed: Default::default(),
            target: Default::default(),
            target_member: Default::default(),
            timestamp: Default::default(),
        }
    }
}
