/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgileSharingSettings : Stores users and groups that have access to an agile board.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum AgileSharingSettings {
}




