/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllUsersGroup : Represents a group containing all users including guest.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllUsersGroup {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "ringId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ring_id: Option<Option<String>>,
    #[serde(rename = "usersCount", skip_serializing_if = "Option::is_none")]
    pub users_count: Option<i64>,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "allUsersGroup", skip_serializing_if = "Option::is_none")]
    pub all_users_group: Option<bool>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<models::User>>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl AllUsersGroup {
    /// Represents a group containing all users including guest.
    pub fn new() -> AllUsersGroup {
        AllUsersGroup {
            id: None,
            name: None,
            ring_id: None,
            users_count: None,
            icon: None,
            all_users_group: None,
            users: None,
            dollar_type: None,
        }
    }
}

