/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Article :
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Article {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<models::ArticleAttachment>>,
    #[serde(
        rename = "content",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub content: Option<Option<String>>,
    #[serde(rename = "reporter", skip_serializing_if = "Option::is_none")]
    pub reporter: Option<Box<models::User>>,
    #[serde(
        rename = "summary",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub summary: Option<Option<String>>,
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<Box<models::Visibility>>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "childArticles", skip_serializing_if = "Option::is_none")]
    pub child_articles: Option<Vec<models::Article>>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<Vec<models::ArticleComment>>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<i64>,
    #[serde(rename = "externalArticle", skip_serializing_if = "Option::is_none")]
    pub external_article: Option<Box<models::ExternalArticle>>,
    #[serde(rename = "hasChildren", skip_serializing_if = "Option::is_none")]
    pub has_children: Option<bool>,
    #[serde(rename = "hasStar", skip_serializing_if = "Option::is_none")]
    pub has_star: Option<bool>,
    #[serde(rename = "idReadable", skip_serializing_if = "Option::is_none")]
    pub id_readable: Option<String>,
    #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
    pub ordinal: Option<i64>,
    #[serde(rename = "parentArticle", skip_serializing_if = "Option::is_none")]
    pub parent_article: Option<Box<models::Article>>,
    #[serde(rename = "pinnedComments", skip_serializing_if = "Option::is_none")]
    pub pinned_comments: Option<Vec<models::ArticleComment>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<models::Tag>>,
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<i64>,
    #[serde(rename = "updatedBy", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Box<models::User>>,
}

impl Article {
    ///
    pub fn new() -> Article {
        Article {
            id: None,
            attachments: None,
            content: None,
            reporter: None,
            summary: None,
            visibility: None,
            dollar_type: None,
            child_articles: None,
            comments: None,
            created: None,
            external_article: None,
            has_children: None,
            has_star: None,
            id_readable: None,
            ordinal: None,
            parent_article: None,
            pinned_comments: None,
            project: None,
            tags: None,
            updated: None,
            updated_by: None,
        }
    }
}
