/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssignedRole : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssignedRole {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Box<models::Role>>,
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<Box<models::AccessScope>>,
    #[serde(rename = "holder", skip_serializing_if = "Option::is_none")]
    pub holder: Option<serde_json::Value>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl AssignedRole {
    /// 
    pub fn new() -> AssignedRole {
        AssignedRole {
            id: None,
            role: None,
            scope: None,
            holder: None,
            dollar_type: None,
        }
    }
}

