/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AttributeBasedSwimlaneSettings :
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttributeBasedSwimlaneSettings {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<Box<models::FilterField>>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<models::SwimlaneEntityAttributeValue>>,
}

impl AttributeBasedSwimlaneSettings {
    ///
    pub fn new() -> AttributeBasedSwimlaneSettings {
        AttributeBasedSwimlaneSettings {
            id: None,
            enabled: None,
            dollar_type: None,
            field: None,
            values: None,
        }
    }
}
