/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BaseArticle : Represents a base article entity.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum BaseArticle {
    #[serde(rename = "Article")]
    Article {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
        attachments: Option<Vec<models::ArticleAttachment>>,
        #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
        content: Option<String>,
        #[serde(rename = "reporter", skip_serializing_if = "Option::is_none")]
        reporter: Option<Box<models::User>>,
        #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
        summary: Option<String>,
        #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
        visibility: Option<Box<models::Visibility>>,
    },
    #[serde(rename = "BaseArticle")]
    BaseArticle {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
        attachments: Option<Vec<models::ArticleAttachment>>,
        #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
        content: Option<String>,
        #[serde(rename = "reporter", skip_serializing_if = "Option::is_none")]
        reporter: Option<Box<models::User>>,
        #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
        summary: Option<String>,
        #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
        visibility: Option<Box<models::Visibility>>,
    },
}

impl Default for BaseArticle {
    fn default() -> Self {
        Self::Article {
            id: Default::default(),
            attachments: Default::default(),
            content: Default::default(),
            reporter: Default::default(),
            summary: Default::default(),
            visibility: Default::default(),
        }
    }
}
