/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BaseWorkItem : Represents a basic ancestor for work items.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum BaseWorkItem {
    #[serde(rename="BaseWorkItem")]
    BaseWorkItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
    #[serde(rename="IssueWorkItem")]
    IssueWorkItem {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
}

impl Default for BaseWorkItem {
    fn default() -> Self {
        Self::BaseWorkItem {
            id: Default::default(),
        }
        
    }
}


