/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Bundle :
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum Bundle {
    #[serde(rename = "BaseBundle")]
    BaseBundle {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "isUpdateable", skip_serializing_if = "Option::is_none")]
        is_updateable: Option<bool>,
    },
    #[serde(rename = "BuildBundle")]
    BuildBundle {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "isUpdateable", skip_serializing_if = "Option::is_none")]
        is_updateable: Option<bool>,
    },
    #[serde(rename = "Bundle")]
    Bundle {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "isUpdateable", skip_serializing_if = "Option::is_none")]
        is_updateable: Option<bool>,
    },
    #[serde(rename = "EnumBundle")]
    EnumBundle {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "isUpdateable", skip_serializing_if = "Option::is_none")]
        is_updateable: Option<bool>,
    },
    #[serde(rename = "OwnedBundle")]
    OwnedBundle {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "isUpdateable", skip_serializing_if = "Option::is_none")]
        is_updateable: Option<bool>,
    },
    #[serde(rename = "StateBundle")]
    StateBundle {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "isUpdateable", skip_serializing_if = "Option::is_none")]
        is_updateable: Option<bool>,
    },
    #[serde(rename = "UserBundle")]
    UserBundle {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "isUpdateable", skip_serializing_if = "Option::is_none")]
        is_updateable: Option<bool>,
    },
    #[serde(rename = "VersionBundle")]
    VersionBundle {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "isUpdateable", skip_serializing_if = "Option::is_none")]
        is_updateable: Option<bool>,
    },
}

impl Default for Bundle {
    fn default() -> Self {
        Self::BaseBundle {
            id: Default::default(),
            is_updateable: Default::default(),
        }
    }
}
