/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BundleElement : Represents a field value in YouTrack.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum BundleElement {
    #[serde(rename="BuildBundleElement")]
    BuildBundleElement {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "bundle", skip_serializing_if = "Option::is_none")]
        bundle: Option<Box<models::Bundle>>,
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
        #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
        archived: Option<bool>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
        color: Option<Box<models::FieldStyle>>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
    },
    #[serde(rename="BundleElement")]
    BundleElement {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "bundle", skip_serializing_if = "Option::is_none")]
        bundle: Option<Box<models::Bundle>>,
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
        #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
        archived: Option<bool>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
        color: Option<Box<models::FieldStyle>>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
    },
    #[serde(rename="EnumBundleElement")]
    EnumBundleElement {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "bundle", skip_serializing_if = "Option::is_none")]
        bundle: Option<Box<models::Bundle>>,
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
        #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
        archived: Option<bool>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
        color: Option<Box<models::FieldStyle>>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
    },
    #[serde(rename="LocalizableBundleElement")]
    LocalizableBundleElement {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "bundle", skip_serializing_if = "Option::is_none")]
        bundle: Option<Box<models::Bundle>>,
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
        #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
        archived: Option<bool>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
        color: Option<Box<models::FieldStyle>>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
    },
    #[serde(rename="OwnedBundleElement")]
    OwnedBundleElement {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "bundle", skip_serializing_if = "Option::is_none")]
        bundle: Option<Box<models::Bundle>>,
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
        #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
        archived: Option<bool>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
        color: Option<Box<models::FieldStyle>>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
    },
    #[serde(rename="StateBundleElement")]
    StateBundleElement {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "bundle", skip_serializing_if = "Option::is_none")]
        bundle: Option<Box<models::Bundle>>,
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
        #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
        archived: Option<bool>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
        color: Option<Box<models::FieldStyle>>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
    },
    #[serde(rename="VersionBundleElement")]
    VersionBundleElement {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "bundle", skip_serializing_if = "Option::is_none")]
        bundle: Option<Box<models::Bundle>>,
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
        #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
        archived: Option<bool>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
        color: Option<Box<models::FieldStyle>>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
    },
}

impl Default for BundleElement {
    fn default() -> Self {
        Self::BuildBundleElement {
            id: Default::default(),
            name: Default::default(),
            bundle: Default::default(),
            description: Default::default(),
            archived: Default::default(),
            ordinal: Default::default(),
            color: Default::default(),
            has_running_job: Default::default(),
        }
        
    }
}


