/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChangesProcessor : The basic entity that represents a VCS or a build server integration configured for a project.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum ChangesProcessor {
    #[serde(rename = "BitBucketChangesProcessor")]
    BitBucketChangesProcessor {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
        server: Option<Box<models::VcsServer>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "relatedProjects", skip_serializing_if = "Option::is_none")]
        related_projects: Option<Vec<models::Project>>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
        #[serde(rename = "visibleForGroups", skip_serializing_if = "Option::is_none")]
        visible_for_groups: Option<Vec<models::UserGroup>>,
        #[serde(rename = "addComments", skip_serializing_if = "Option::is_none")]
        add_comments: Option<bool>,
        #[serde(
            rename = "lookupIssuesInBranchName",
            skip_serializing_if = "Option::is_none"
        )]
        lookup_issues_in_branch_name: Option<bool>,
    },
    #[serde(rename = "BitbucketStandaloneChangesProcessor")]
    BitbucketStandaloneChangesProcessor {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
        server: Option<Box<models::VcsServer>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "relatedProjects", skip_serializing_if = "Option::is_none")]
        related_projects: Option<Vec<models::Project>>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
        #[serde(rename = "visibleForGroups", skip_serializing_if = "Option::is_none")]
        visible_for_groups: Option<Vec<models::UserGroup>>,
        #[serde(rename = "addComments", skip_serializing_if = "Option::is_none")]
        add_comments: Option<bool>,
        #[serde(
            rename = "lookupIssuesInBranchName",
            skip_serializing_if = "Option::is_none"
        )]
        lookup_issues_in_branch_name: Option<bool>,
    },
    #[serde(rename = "ChangesProcessor")]
    ChangesProcessor {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
        server: Option<Box<models::VcsServer>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "relatedProjects", skip_serializing_if = "Option::is_none")]
        related_projects: Option<Vec<models::Project>>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
        #[serde(rename = "visibleForGroups", skip_serializing_if = "Option::is_none")]
        visible_for_groups: Option<Vec<models::UserGroup>>,
        #[serde(rename = "addComments", skip_serializing_if = "Option::is_none")]
        add_comments: Option<bool>,
        #[serde(
            rename = "lookupIssuesInBranchName",
            skip_serializing_if = "Option::is_none"
        )]
        lookup_issues_in_branch_name: Option<bool>,
    },
    #[serde(rename = "GitHubChangesProcessor")]
    GitHubChangesProcessor {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
        server: Option<Box<models::VcsServer>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "relatedProjects", skip_serializing_if = "Option::is_none")]
        related_projects: Option<Vec<models::Project>>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
        #[serde(rename = "visibleForGroups", skip_serializing_if = "Option::is_none")]
        visible_for_groups: Option<Vec<models::UserGroup>>,
        #[serde(rename = "addComments", skip_serializing_if = "Option::is_none")]
        add_comments: Option<bool>,
        #[serde(
            rename = "lookupIssuesInBranchName",
            skip_serializing_if = "Option::is_none"
        )]
        lookup_issues_in_branch_name: Option<bool>,
    },
    #[serde(rename = "GitLabChangesProcessor")]
    GitLabChangesProcessor {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
        server: Option<Box<models::VcsServer>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "relatedProjects", skip_serializing_if = "Option::is_none")]
        related_projects: Option<Vec<models::Project>>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
        #[serde(rename = "visibleForGroups", skip_serializing_if = "Option::is_none")]
        visible_for_groups: Option<Vec<models::UserGroup>>,
        #[serde(rename = "addComments", skip_serializing_if = "Option::is_none")]
        add_comments: Option<bool>,
        #[serde(
            rename = "lookupIssuesInBranchName",
            skip_serializing_if = "Option::is_none"
        )]
        lookup_issues_in_branch_name: Option<bool>,
    },
    #[serde(rename = "GiteaChangesProcessor")]
    GiteaChangesProcessor {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
        server: Option<Box<models::VcsServer>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "relatedProjects", skip_serializing_if = "Option::is_none")]
        related_projects: Option<Vec<models::Project>>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
        #[serde(rename = "visibleForGroups", skip_serializing_if = "Option::is_none")]
        visible_for_groups: Option<Vec<models::UserGroup>>,
        #[serde(rename = "addComments", skip_serializing_if = "Option::is_none")]
        add_comments: Option<bool>,
        #[serde(
            rename = "lookupIssuesInBranchName",
            skip_serializing_if = "Option::is_none"
        )]
        lookup_issues_in_branch_name: Option<bool>,
    },
    #[serde(rename = "GogsChangesProcessor")]
    GogsChangesProcessor {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
        server: Option<Box<models::VcsServer>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "relatedProjects", skip_serializing_if = "Option::is_none")]
        related_projects: Option<Vec<models::Project>>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
        #[serde(rename = "visibleForGroups", skip_serializing_if = "Option::is_none")]
        visible_for_groups: Option<Vec<models::UserGroup>>,
        #[serde(rename = "addComments", skip_serializing_if = "Option::is_none")]
        add_comments: Option<bool>,
        #[serde(
            rename = "lookupIssuesInBranchName",
            skip_serializing_if = "Option::is_none"
        )]
        lookup_issues_in_branch_name: Option<bool>,
    },
    #[serde(rename = "JenkinsChangesProcessor")]
    JenkinsChangesProcessor {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
        server: Option<Box<models::VcsServer>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "relatedProjects", skip_serializing_if = "Option::is_none")]
        related_projects: Option<Vec<models::Project>>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
        #[serde(rename = "visibleForGroups", skip_serializing_if = "Option::is_none")]
        visible_for_groups: Option<Vec<models::UserGroup>>,
        #[serde(rename = "addComments", skip_serializing_if = "Option::is_none")]
        add_comments: Option<bool>,
        #[serde(
            rename = "lookupIssuesInBranchName",
            skip_serializing_if = "Option::is_none"
        )]
        lookup_issues_in_branch_name: Option<bool>,
    },
    #[serde(rename = "SpaceChangesProcessor")]
    SpaceChangesProcessor {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
        server: Option<Box<models::VcsServer>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "relatedProjects", skip_serializing_if = "Option::is_none")]
        related_projects: Option<Vec<models::Project>>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
        #[serde(rename = "visibleForGroups", skip_serializing_if = "Option::is_none")]
        visible_for_groups: Option<Vec<models::UserGroup>>,
        #[serde(rename = "addComments", skip_serializing_if = "Option::is_none")]
        add_comments: Option<bool>,
        #[serde(
            rename = "lookupIssuesInBranchName",
            skip_serializing_if = "Option::is_none"
        )]
        lookup_issues_in_branch_name: Option<bool>,
    },
    #[serde(rename = "TeamcityChangesProcessor")]
    TeamcityChangesProcessor {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
        server: Option<Box<models::VcsServer>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "relatedProjects", skip_serializing_if = "Option::is_none")]
        related_projects: Option<Vec<models::Project>>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
        #[serde(rename = "visibleForGroups", skip_serializing_if = "Option::is_none")]
        visible_for_groups: Option<Vec<models::UserGroup>>,
        #[serde(rename = "addComments", skip_serializing_if = "Option::is_none")]
        add_comments: Option<bool>,
        #[serde(
            rename = "lookupIssuesInBranchName",
            skip_serializing_if = "Option::is_none"
        )]
        lookup_issues_in_branch_name: Option<bool>,
    },
    #[serde(rename = "VcsHostingChangesProcessor")]
    VcsHostingChangesProcessor {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
        server: Option<Box<models::VcsServer>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "relatedProjects", skip_serializing_if = "Option::is_none")]
        related_projects: Option<Vec<models::Project>>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
        #[serde(rename = "visibleForGroups", skip_serializing_if = "Option::is_none")]
        visible_for_groups: Option<Vec<models::UserGroup>>,
        #[serde(rename = "addComments", skip_serializing_if = "Option::is_none")]
        add_comments: Option<bool>,
        #[serde(
            rename = "lookupIssuesInBranchName",
            skip_serializing_if = "Option::is_none"
        )]
        lookup_issues_in_branch_name: Option<bool>,
    },
}

impl Default for ChangesProcessor {
    fn default() -> Self {
        Self::BitBucketChangesProcessor {
            id: Default::default(),
            server: Default::default(),
            project: Default::default(),
            related_projects: Default::default(),
            enabled: Default::default(),
            visible_for_groups: Default::default(),
            add_comments: Default::default(),
            lookup_issues_in_branch_name: Default::default(),
        }
    }
}
