/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ColorCoding : Describes rules that define which colors are used for cards on the agile board.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum ColorCoding {
    #[serde(rename="ColorCoding")]
    ColorCoding {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
    #[serde(rename="FieldBasedColorCoding")]
    FieldBasedColorCoding {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
    #[serde(rename="ProjectBasedColorCoding")]
    ProjectBasedColorCoding {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
}

impl Default for ColorCoding {
    fn default() -> Self {
        Self::ColorCoding {
            id: Default::default(),
        }
        
    }
}


