/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommandUnlimitedVisibility : Comment is visible for all the users who can read the issue.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommandUnlimitedVisibility {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl CommandUnlimitedVisibility {
    /// Comment is visible for all the users who can read the issue.
    pub fn new() -> CommandUnlimitedVisibility {
        CommandUnlimitedVisibility {
            id: None,
            dollar_type: None,
        }
    }
}
