/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommandLimitedVisibility : Stores the restricted visibility settings for the command.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommandLimitedVisibility {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "permittedGroups", skip_serializing_if = "Option::is_none")]
    pub permitted_groups: Option<Vec<models::UserGroup>>,
    #[serde(rename = "permittedUsers", skip_serializing_if = "Option::is_none")]
    pub permitted_users: Option<Vec<models::User>>,
}

impl CommandLimitedVisibility {
    /// Stores the restricted visibility settings for the command.
    pub fn new() -> CommandLimitedVisibility {
        CommandLimitedVisibility {
            id: None,
            dollar_type: None,
            permitted_groups: None,
            permitted_users: None,
        }
    }
}
