/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommandVisibility : Visibility settings of the comment that is added along with the command.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum CommandVisibility {
    #[serde(rename="CommandLimitedVisibility")]
    CommandLimitedVisibility {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
    #[serde(rename="CommandUnlimitedVisibility")]
    CommandUnlimitedVisibility {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
    #[serde(rename="CommandVisibility")]
    CommandVisibility {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
}

impl Default for CommandVisibility {
    fn default() -> Self {
        Self::CommandLimitedVisibility {
            id: Default::default(),
        }
        
    }
}


