/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomFilterField : Represents a custom field of the issue.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFilterField {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "presentation", skip_serializing_if = "Option::is_none")]
    pub presentation: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "customField", skip_serializing_if = "Option::is_none")]
    pub custom_field: Option<Box<models::CustomField>>,
}

impl CustomFilterField {
    /// Represents a custom field of the issue.
    pub fn new() -> CustomFilterField {
        CustomFilterField {
            id: None,
            presentation: None,
            name: None,
            dollar_type: None,
            custom_field: None,
        }
    }
}
