/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomFieldCondition : Represents the condition for showing a custom field.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum CustomFieldCondition {
    #[serde(rename = "CustomFieldCondition")]
    CustomFieldCondition {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
        parent: Option<Box<models::ProjectCustomField>>,
    },
    #[serde(rename = "FieldBasedCondition")]
    FieldBasedCondition {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
        parent: Option<Box<models::ProjectCustomField>>,
    },
}

impl Default for CustomFieldCondition {
    fn default() -> Self {
        Self::CustomFieldCondition {
            id: Default::default(),
            parent: Default::default(),
        }
    }
}
