/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomFieldDefaults :
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum CustomFieldDefaults {
    #[serde(rename = "BuildBundleCustomFieldDefaults")]
    BuildBundleCustomFieldDefaults {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
        parent: Option<Box<models::CustomField>>,
    },
    #[serde(rename = "BundleCustomFieldDefaults")]
    BundleCustomFieldDefaults {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
        parent: Option<Box<models::CustomField>>,
    },
    #[serde(rename = "CustomFieldDefaults")]
    CustomFieldDefaults {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
        parent: Option<Box<models::CustomField>>,
    },
    #[serde(rename = "EnumBundleCustomFieldDefaults")]
    EnumBundleCustomFieldDefaults {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
        parent: Option<Box<models::CustomField>>,
    },
    #[serde(rename = "OwnedBundleCustomFieldDefaults")]
    OwnedBundleCustomFieldDefaults {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
        parent: Option<Box<models::CustomField>>,
    },
    #[serde(rename = "StateBundleCustomFieldDefaults")]
    StateBundleCustomFieldDefaults {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
        parent: Option<Box<models::CustomField>>,
    },
    #[serde(rename = "UserCustomFieldDefaults")]
    UserCustomFieldDefaults {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
        parent: Option<Box<models::CustomField>>,
    },
    #[serde(rename = "VersionBundleCustomFieldDefaults")]
    VersionBundleCustomFieldDefaults {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
        parent: Option<Box<models::CustomField>>,
    },
}

impl Default for CustomFieldDefaults {
    fn default() -> Self {
        Self::BuildBundleCustomFieldDefaults {
            id: Default::default(),
            can_be_empty: Default::default(),
            empty_field_text: Default::default(),
            is_public: Default::default(),
            parent: Default::default(),
        }
    }
}
