/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DatabaseBackupSettings : 
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum DatabaseBackupSettings {
}



/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ArchiveFormat {
    #[serde(rename = "TAR_GZ")]
    TarGz,
    #[serde(rename = "ZIP")]
    Zip,
}

impl Default for ArchiveFormat {
    fn default() -> ArchiveFormat {
        Self::TarGz
    }
}

