/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DatabaseAttributeValue : Represents string reference to the value.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum DatabaseAttributeValue {
    #[serde(rename = "AgileColumnFieldValue")]
    AgileColumnFieldValue {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
    #[serde(rename = "DatabaseAttributeValue")]
    DatabaseAttributeValue {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
    #[serde(rename = "SwimlaneEntityAttributeValue")]
    SwimlaneEntityAttributeValue {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
}

impl Default for DatabaseAttributeValue {
    fn default() -> Self {
        Self::AgileColumnFieldValue {
            id: Default::default(),
        }
    }
}
