/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmailSettings : Represents email settings for this YouTrack installation.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum EmailSettings {
}



/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MailProtocol {
    #[serde(rename = "SMTP")]
    Smtp,
    #[serde(rename = "SMTPS")]
    Smtps,
    #[serde(rename = "SMTP_TLS")]
    SmtpTls,
    #[serde(rename = "MS_GRAPH_API")]
    MsGraphApi,
}

impl Default for MailProtocol {
    fn default() -> MailProtocol {
        Self::Smtp
    }
}

