/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EnumBundleElement :
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnumBundleElement {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "bundle", skip_serializing_if = "Option::is_none")]
    pub bundle: Option<Box<models::Bundle>>,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
    #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
    pub ordinal: Option<i32>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<Box<models::FieldStyle>>,
    #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
    pub has_running_job: Option<bool>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(
        rename = "localizedName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub localized_name: Option<Option<String>>,
}

impl EnumBundleElement {
    ///
    pub fn new() -> EnumBundleElement {
        EnumBundleElement {
            id: None,
            name: None,
            bundle: None,
            description: None,
            archived: None,
            ordinal: None,
            color: None,
            has_running_job: None,
            dollar_type: None,
            localized_name: None,
        }
    }
}
