/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FieldBasedColorCoding : Sets a card color based on a value of some custom field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldBasedColorCoding {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "prototype", skip_serializing_if = "Option::is_none")]
    pub prototype: Option<Box<models::CustomField>>,
}

impl FieldBasedColorCoding {
    /// Sets a card color based on a value of some custom field.
    pub fn new() -> FieldBasedColorCoding {
        FieldBasedColorCoding {
            id: None,
            dollar_type: None,
            prototype: None,
        }
    }
}

