/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FieldBasedCondition : Represents the condition for showing a custom field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldBasedCondition {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Box<models::ProjectCustomField>>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<Box<models::BundleProjectCustomField>>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<models::BundleElement>>,
    #[serde(rename = "showForNullValue", skip_serializing_if = "Option::is_none")]
    pub show_for_null_value: Option<bool>,
}

impl FieldBasedCondition {
    /// Represents the condition for showing a custom field.
    pub fn new() -> FieldBasedCondition {
        FieldBasedCondition {
            id: None,
            parent: None,
            dollar_type: None,
            field: None,
            values: None,
            show_for_null_value: None,
        }
    }
}

