/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilterField : Represents an issue property, which can be a predefined field, a custom field, a link, and so on.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum FilterField {
    #[serde(rename = "CustomFilterField")]
    CustomFilterField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "presentation", skip_serializing_if = "Option::is_none")]
        presentation: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
    },
    #[serde(rename = "FilterField")]
    FilterField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "presentation", skip_serializing_if = "Option::is_none")]
        presentation: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
    },
    #[serde(rename = "PredefinedFilterField")]
    PredefinedFilterField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "presentation", skip_serializing_if = "Option::is_none")]
        presentation: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
    },
}

impl Default for FilterField {
    fn default() -> Self {
        Self::CustomFilterField {
            id: Default::default(),
            presentation: Default::default(),
            name: Default::default(),
        }
    }
}
