/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GiteaServer : Represents a Gitea server.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GiteaServer {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl GiteaServer {
    /// Represents a Gitea server.
    pub fn new() -> GiteaServer {
        GiteaServer {
            id: None,
            url: None,
            dollar_type: None,
        }
    }
}
