/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GroupProjectCustomField : Represents project settings for a group custom field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupProjectCustomField {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<Box<models::CustomField>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
    #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
    pub can_be_empty: Option<bool>,
    #[serde(rename = "emptyFieldText", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub empty_field_text: Option<Option<String>>,
    #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
    pub ordinal: Option<i32>,
    #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
    pub has_running_job: Option<bool>,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<Box<models::CustomFieldCondition>>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "defaultValues", skip_serializing_if = "Option::is_none")]
    pub default_values: Option<Vec<models::UserGroup>>,
}

impl GroupProjectCustomField {
    /// Represents project settings for a group custom field.
    pub fn new() -> GroupProjectCustomField {
        GroupProjectCustomField {
            id: None,
            field: None,
            project: None,
            can_be_empty: None,
            empty_field_text: None,
            ordinal: None,
            is_public: None,
            has_running_job: None,
            condition: None,
            dollar_type: None,
            default_values: None,
        }
    }
}

