/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IssueLink : 
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum IssueLink {
}



/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "OUTWARD")]
    Outward,
    #[serde(rename = "INWARD")]
    Inward,
    #[serde(rename = "BOTH")]
    Both,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Outward
    }
}

