/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IssueCustomField : 
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum IssueCustomField {
    #[serde(rename="DateIssueCustomField")]
    DateIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="IssueCustomField")]
    IssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="MultiBuildIssueCustomField")]
    MultiBuildIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="MultiEnumIssueCustomField")]
    MultiEnumIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="MultiGroupIssueCustomField")]
    MultiGroupIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="MultiOwnedIssueCustomField")]
    MultiOwnedIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="MultiUserIssueCustomField")]
    MultiUserIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="MultiValueIssueCustomField")]
    DatabaseMultiValueIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="MultiVersionIssueCustomField")]
    MultiVersionIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="PeriodIssueCustomField")]
    PeriodIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="SimpleIssueCustomField")]
    SimpleIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="SingleBuildIssueCustomField")]
    SingleBuildIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="SingleEnumIssueCustomField")]
    SingleEnumIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="SingleGroupIssueCustomField")]
    SingleGroupIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="SingleOwnedIssueCustomField")]
    SingleOwnedIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="SingleUserIssueCustomField")]
    SingleUserIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="SingleValueIssueCustomField")]
    DatabaseSingleValueIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="SingleVersionIssueCustomField")]
    SingleVersionIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="StateIssueCustomField")]
    StateIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="StateMachineIssueCustomField")]
    StateMachineIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
    #[serde(rename="TextIssueCustomField")]
    TextIssueCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
        project_custom_field: Option<Box<models::ProjectCustomField>>,
        #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
        value: Option<serde_json::Value>,
    },
}

impl Default for IssueCustomField {
    fn default() -> Self {
        Self::DateIssueCustomField {
            id: Default::default(),
            name: Default::default(),
            project_custom_field: Default::default(),
            value: Default::default(),
        }
        
    }
}


