/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IssueBasedSwimlaneSettings : Swimlane settings for the case, when each swimlane is represented by an issue and contains this issue's subtasks.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueBasedSwimlaneSettings {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<Box<models::FilterField>>,
    #[serde(rename = "defaultCardType", skip_serializing_if = "Option::is_none")]
    pub default_card_type: Option<Box<models::SwimlaneValue>>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<models::SwimlaneValue>>,
}

impl IssueBasedSwimlaneSettings {
    /// Swimlane settings for the case, when each swimlane is represented by an issue and contains this issue's subtasks.
    pub fn new() -> IssueBasedSwimlaneSettings {
        IssueBasedSwimlaneSettings {
            id: None,
            enabled: None,
            dollar_type: None,
            field: None,
            default_card_type: None,
            values: None,
        }
    }
}
