/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IssueFolder : Represents an issue folder, such as a project, a saved search, or a tag.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum IssueFolder {
    #[serde(rename="IssueFolder")]
    IssueFolder {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
    },
    #[serde(rename="IssueTag")]
    IssueTag {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
    },
    #[serde(rename="Project")]
    Project {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
    },
    #[serde(rename="SavedQuery")]
    SavedQuery {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
    },
    #[serde(rename="Tag")]
    Tag {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
    },
    #[serde(rename="WatchFolder")]
    WatchFolder {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
    },
}

impl Default for IssueFolder {
    fn default() -> Self {
        Self::IssueFolder {
            id: Default::default(),
            name: Default::default(),
        }
        
    }
}


