/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IssueLink : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueLink {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "direction", skip_serializing_if = "Option::is_none")]
    pub direction: Option<Direction>,
    #[serde(rename = "linkType", skip_serializing_if = "Option::is_none")]
    pub link_type: Option<Box<models::IssueLinkType>>,
    #[serde(rename = "issues", skip_serializing_if = "Option::is_none")]
    pub issues: Option<Vec<models::Issue>>,
    #[serde(rename = "trimmedIssues", skip_serializing_if = "Option::is_none")]
    pub trimmed_issues: Option<Vec<models::Issue>>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl IssueLink {
    /// 
    pub fn new() -> IssueLink {
        IssueLink {
            id: None,
            direction: None,
            link_type: None,
            issues: None,
            trimmed_issues: None,
            dollar_type: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "OUTWARD")]
    Outward,
    #[serde(rename = "INWARD")]
    Inward,
    #[serde(rename = "BOTH")]
    Both,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Outward
    }
}

