/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JenkinsChangesProcessor : Represents a Jenkins integration configured for a project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JenkinsChangesProcessor {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
    pub server: Option<Box<models::JenkinsServer>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
    #[serde(rename = "relatedProjects", skip_serializing_if = "Option::is_none")]
    pub related_projects: Option<Vec<models::Project>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "visibleForGroups", skip_serializing_if = "Option::is_none")]
    pub visible_for_groups: Option<Vec<models::UserGroup>>,
    #[serde(rename = "addComments", skip_serializing_if = "Option::is_none")]
    pub add_comments: Option<bool>,
    #[serde(
        rename = "lookupIssuesInBranchName",
        skip_serializing_if = "Option::is_none"
    )]
    pub lookup_issues_in_branch_name: Option<bool>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl JenkinsChangesProcessor {
    /// Represents a Jenkins integration configured for a project.
    pub fn new() -> JenkinsChangesProcessor {
        JenkinsChangesProcessor {
            id: None,
            server: None,
            project: None,
            related_projects: None,
            enabled: None,
            visible_for_groups: None,
            add_comments: None,
            lookup_issues_in_branch_name: None,
            dollar_type: None,
        }
    }
}
