/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LocaleSettings : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocaleSettings {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<Box<models::LocaleDescriptor>>,
    #[serde(rename = "isRTL", skip_serializing_if = "Option::is_none")]
    pub is_rtl: Option<bool>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl LocaleSettings {
    /// 
    pub fn new() -> LocaleSettings {
        LocaleSettings {
            id: None,
            locale: None,
            is_rtl: None,
            dollar_type: None,
        }
    }
}

