/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MultiVersionIssueCustomField : Represents a multi-value version-type custom field in the issue.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiVersionIssueCustomField {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
    pub project_custom_field: Option<Box<models::ProjectCustomField>>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Vec<models::VersionBundleElement>>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl MultiVersionIssueCustomField {
    /// Represents a multi-value version-type custom field in the issue.
    pub fn new() -> MultiVersionIssueCustomField {
        MultiVersionIssueCustomField {
            id: None,
            name: None,
            project_custom_field: None,
            value: None,
            dollar_type: None,
        }
    }
}
