/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Permission : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Permission {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "permissionEntityType", skip_serializing_if = "Option::is_none")]
    pub permission_entity_type: Option<String>,
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    #[serde(rename = "impliedPermissions", skip_serializing_if = "Option::is_none")]
    pub implied_permissions: Option<Vec<models::Permission>>,
    #[serde(rename = "dependentPermissions", skip_serializing_if = "Option::is_none")]
    pub dependent_permissions: Option<Vec<models::Permission>>,
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<serde_json::Value>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl Permission {
    /// 
    pub fn new() -> Permission {
        Permission {
            id: None,
            name: None,
            description: None,
            permission_entity_type: None,
            operation: None,
            implied_permissions: None,
            dependent_permissions: None,
            scope: None,
            dollar_type: None,
        }
    }
}

