/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectBasedColorCoding : Lets you set a color for a card based on its project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectBasedColorCoding {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "projectColors", skip_serializing_if = "Option::is_none")]
    pub project_colors: Option<Vec<models::ProjectColor>>,
}

impl ProjectBasedColorCoding {
    /// Lets you set a color for a card based on its project.
    pub fn new() -> ProjectBasedColorCoding {
        ProjectBasedColorCoding {
            id: None,
            dollar_type: None,
            project_colors: None,
        }
    }
}
