/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectScope : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectScope {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
}

impl ProjectScope {
    /// 
    pub fn new() -> ProjectScope {
        ProjectScope {
            id: None,
            dollar_type: None,
            project: None,
        }
    }
}

