/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectCustomField : 
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum ProjectCustomField {
    #[serde(rename="BuildProjectCustomField")]
    BuildProjectCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::CustomField>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
        #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
        condition: Option<Box<models::CustomFieldCondition>>,
    },
    #[serde(rename="BundleProjectCustomField")]
    BundleProjectCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::CustomField>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
        #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
        condition: Option<Box<models::CustomFieldCondition>>,
    },
    #[serde(rename="EnumProjectCustomField")]
    EnumProjectCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::CustomField>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
        #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
        condition: Option<Box<models::CustomFieldCondition>>,
    },
    #[serde(rename="GroupProjectCustomField")]
    GroupProjectCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::CustomField>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
        #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
        condition: Option<Box<models::CustomFieldCondition>>,
    },
    #[serde(rename="OwnedProjectCustomField")]
    OwnedProjectCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::CustomField>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
        #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
        condition: Option<Box<models::CustomFieldCondition>>,
    },
    #[serde(rename="PeriodProjectCustomField")]
    PeriodProjectCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::CustomField>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
        #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
        condition: Option<Box<models::CustomFieldCondition>>,
    },
    #[serde(rename="ProjectCustomField")]
    ProjectCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::CustomField>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
        #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
        condition: Option<Box<models::CustomFieldCondition>>,
    },
    #[serde(rename="SimpleProjectCustomField")]
    SimpleProjectCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::CustomField>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
        #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
        condition: Option<Box<models::CustomFieldCondition>>,
    },
    #[serde(rename="StateProjectCustomField")]
    StateProjectCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::CustomField>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
        #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
        condition: Option<Box<models::CustomFieldCondition>>,
    },
    #[serde(rename="TextProjectCustomField")]
    TextProjectCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::CustomField>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
        #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
        condition: Option<Box<models::CustomFieldCondition>>,
    },
    #[serde(rename="UserProjectCustomField")]
    UserProjectCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::CustomField>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
        #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
        condition: Option<Box<models::CustomFieldCondition>>,
    },
    #[serde(rename="VersionProjectCustomField")]
    VersionProjectCustomField {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
        field: Option<Box<models::CustomField>>,
        #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
        project: Option<Box<models::Project>>,
        #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
        can_be_empty: Option<bool>,
        #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
        empty_field_text: Option<String>,
        #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
        ordinal: Option<i32>,
        #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
        is_public: Option<bool>,
        #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
        has_running_job: Option<bool>,
        #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
        condition: Option<Box<models::CustomFieldCondition>>,
    },
}

impl Default for ProjectCustomField {
    fn default() -> Self {
        Self::BuildProjectCustomField {
            id: Default::default(),
            field: Default::default(),
            project: Default::default(),
            can_be_empty: Default::default(),
            empty_field_text: Default::default(),
            ordinal: Default::default(),
            is_public: Default::default(),
            has_running_job: Default::default(),
            condition: Default::default(),
        }
        
    }
}


