/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SimpleProjectCustomField : Represents project settings for the fields of the following types: `integer`, `float`, `date`, `date and time`, `string`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleProjectCustomField {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<Box<models::CustomField>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
    #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
    pub can_be_empty: Option<bool>,
    #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
    pub empty_field_text: Option<String>,
    #[serde(rename = "ordinal", skip_serializing_if = "Option::is_none")]
    pub ordinal: Option<i32>,
    #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    #[serde(rename = "hasRunningJob", skip_serializing_if = "Option::is_none")]
    pub has_running_job: Option<bool>,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<Box<models::CustomFieldCondition>>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl SimpleProjectCustomField {
    /// Represents project settings for the fields of the following types: `integer`, `float`, `date`, `date and time`, `string`.
    pub fn new() -> SimpleProjectCustomField {
        SimpleProjectCustomField {
            id: None,
            field: None,
            project: None,
            can_be_empty: None,
            empty_field_text: None,
            ordinal: None,
            is_public: None,
            has_running_job: None,
            condition: None,
            dollar_type: None,
        }
    }
}

