/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StateMachineIssueCustomField : Represents the issue custom field that is managed by a state-machine rule in workflow.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StateMachineIssueCustomField {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "projectCustomField", skip_serializing_if = "Option::is_none")]
    pub project_custom_field: Option<Box<models::ProjectCustomField>>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "event", skip_serializing_if = "Option::is_none")]
    pub event: Option<Box<models::Event>>,
    #[serde(rename = "possibleEvents", skip_serializing_if = "Option::is_none")]
    pub possible_events: Option<Vec<models::Event>>,
}

impl StateMachineIssueCustomField {
    /// Represents the issue custom field that is managed by a state-machine rule in workflow.
    pub fn new() -> StateMachineIssueCustomField {
        StateMachineIssueCustomField {
            id: None,
            name: None,
            project_custom_field: None,
            value: None,
            dollar_type: None,
            event: None,
            possible_events: None,
        }
    }
}
