/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SwimlaneSettings : Base entity for different swimlane settings
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum SwimlaneSettings {
    #[serde(rename="AttributeBasedSwimlaneSettings")]
    AttributeBasedSwimlaneSettings {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
    },
    #[serde(rename="IssueBasedSwimlaneSettings")]
    IssueBasedSwimlaneSettings {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
    },
    #[serde(rename="SwimlaneSettings")]
    SwimlaneSettings {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
        enabled: Option<bool>,
    },
}

impl Default for SwimlaneSettings {
    fn default() -> Self {
        Self::AttributeBasedSwimlaneSettings {
            id: Default::default(),
            enabled: Default::default(),
        }
        
    }
}


