/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SwimlaneEntityAttributeValue : Represents a single swimlane in case of AttributeBasedSwimlaneSettings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwimlaneEntityAttributeValue {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "isResolved", skip_serializing_if = "Option::is_none")]
    pub is_resolved: Option<bool>,
}

impl SwimlaneEntityAttributeValue {
    /// Represents a single swimlane in case of AttributeBasedSwimlaneSettings.
    pub fn new() -> SwimlaneEntityAttributeValue {
        SwimlaneEntityAttributeValue {
            id: None,
            dollar_type: None,
            name: None,
            is_resolved: None,
        }
    }
}
