/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SwimlaneValue : Represents single swimlane in case of IssueBasedSwimlaneSettings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwimlaneValue {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl SwimlaneValue {
    /// Represents single swimlane in case of IssueBasedSwimlaneSettings.
    pub fn new() -> SwimlaneValue {
        SwimlaneValue {
            id: None,
            name: None,
            dollar_type: None,
        }
    }
}

