/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Tag : 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tag {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<models::User>>,
    #[serde(rename = "visibleFor", skip_serializing_if = "Option::is_none")]
    pub visible_for: Option<Box<models::UserGroup>>,
    #[serde(rename = "updateableBy", skip_serializing_if = "Option::is_none")]
    pub updateable_by: Option<Box<models::UserGroup>>,
    #[serde(rename = "readSharingSettings", skip_serializing_if = "Option::is_none")]
    pub read_sharing_settings: Option<Box<models::WatchFolderSharingSettings>>,
    #[serde(rename = "updateSharingSettings", skip_serializing_if = "Option::is_none")]
    pub update_sharing_settings: Option<Box<models::WatchFolderSharingSettings>>,
    #[serde(rename = "issues", skip_serializing_if = "Option::is_none")]
    pub issues: Option<Vec<models::Issue>>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<Box<models::FieldStyle>>,
    #[serde(rename = "untagOnResolve", skip_serializing_if = "Option::is_none")]
    pub untag_on_resolve: Option<bool>,
    #[serde(rename = "tagSharingSettings", skip_serializing_if = "Option::is_none")]
    pub tag_sharing_settings: Option<Box<models::TagSharingSettings>>,
}

impl Tag {
    /// 
    pub fn new() -> Tag {
        Tag {
            id: None,
            name: None,
            dollar_type: None,
            owner: None,
            visible_for: None,
            updateable_by: None,
            read_sharing_settings: None,
            update_sharing_settings: None,
            issues: None,
            color: None,
            untag_on_resolve: None,
            tag_sharing_settings: None,
        }
    }
}

