/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TeamcityServer : Represents a TeamCity server.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamcityServer {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl TeamcityServer {
    /// Represents a TeamCity server.
    pub fn new() -> TeamcityServer {
        TeamcityServer {
            id: None,
            url: None,
            dollar_type: None,
        }
    }
}

