/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TextMarkupActivityItem : Represents a change in a `String`-type attribute with the support of markup: `description` in an Issue or IssueWorkItem, and the `text` of the IssueComment. This entity lets you get the rendered text after the change.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TextMarkupActivityItem {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
    pub added: Option<String>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<Box<models::User>>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Box<models::ActivityCategory>>,
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<Box<models::FilterField>>,
    #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
    pub removed: Option<String>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<serde_json::Value>,
    #[serde(rename = "targetMember", skip_serializing_if = "Option::is_none")]
    pub target_member: Option<String>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "markup", skip_serializing_if = "Option::is_none")]
    pub markup: Option<String>,
}

impl TextMarkupActivityItem {
    /// Represents a change in a `String`-type attribute with the support of markup: `description` in an Issue or IssueWorkItem, and the `text` of the IssueComment. This entity lets you get the rendered text after the change.
    pub fn new() -> TextMarkupActivityItem {
        TextMarkupActivityItem {
            id: None,
            added: None,
            author: None,
            category: None,
            field: None,
            removed: None,
            target: None,
            target_member: None,
            timestamp: None,
            dollar_type: None,
            markup: None,
        }
    }
}

