/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserGroup : 
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum UserGroup {
    #[serde(rename="AllUsersGroup")]
    AllUsersGroup {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "ringId", skip_serializing_if = "Option::is_none")]
        ring_id: Option<String>,
        #[serde(rename = "usersCount", skip_serializing_if = "Option::is_none")]
        users_count: Option<i64>,
        #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
        icon: Option<String>,
        #[serde(rename = "allUsersGroup", skip_serializing_if = "Option::is_none")]
        all_users_group: Option<bool>,
        #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
        users: Option<Vec<models::User>>,
    },
    #[serde(rename="NestedGroup")]
    NestedGroup {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "ringId", skip_serializing_if = "Option::is_none")]
        ring_id: Option<String>,
        #[serde(rename = "usersCount", skip_serializing_if = "Option::is_none")]
        users_count: Option<i64>,
        #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
        icon: Option<String>,
        #[serde(rename = "allUsersGroup", skip_serializing_if = "Option::is_none")]
        all_users_group: Option<bool>,
        #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
        users: Option<Vec<models::User>>,
    },
    #[serde(rename="ProjectTeam")]
    ProjectTeam {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "ringId", skip_serializing_if = "Option::is_none")]
        ring_id: Option<String>,
        #[serde(rename = "usersCount", skip_serializing_if = "Option::is_none")]
        users_count: Option<i64>,
        #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
        icon: Option<String>,
        #[serde(rename = "allUsersGroup", skip_serializing_if = "Option::is_none")]
        all_users_group: Option<bool>,
        #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
        users: Option<Vec<models::User>>,
    },
    #[serde(rename="RegisteredUsersGroup")]
    RegisteredUsersGroup {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "ringId", skip_serializing_if = "Option::is_none")]
        ring_id: Option<String>,
        #[serde(rename = "usersCount", skip_serializing_if = "Option::is_none")]
        users_count: Option<i64>,
        #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
        icon: Option<String>,
        #[serde(rename = "allUsersGroup", skip_serializing_if = "Option::is_none")]
        all_users_group: Option<bool>,
        #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
        users: Option<Vec<models::User>>,
    },
    #[serde(rename="UserGroup")]
    UserGroup {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "ringId", skip_serializing_if = "Option::is_none")]
        ring_id: Option<String>,
        #[serde(rename = "usersCount", skip_serializing_if = "Option::is_none")]
        users_count: Option<i64>,
        #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
        icon: Option<String>,
        #[serde(rename = "allUsersGroup", skip_serializing_if = "Option::is_none")]
        all_users_group: Option<bool>,
        #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
        users: Option<Vec<models::User>>,
    },
}

impl Default for UserGroup {
    fn default() -> Self {
        Self::AllUsersGroup {
            id: Default::default(),
            name: Default::default(),
            ring_id: Default::default(),
            users_count: Default::default(),
            icon: Default::default(),
            all_users_group: Default::default(),
            users: Default::default(),
        }
        
    }
}


