/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserType : The type of the user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserType {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl UserType {
    /// The type of the user.
    pub fn new() -> UserType {
        UserType {
            id: None,
            dollar_type: None,
        }
    }
}

