/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// User : 
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum User {
    #[serde(rename="Me")]
    Me {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "login", skip_serializing_if = "Option::is_none")]
        login: Option<String>,
        #[serde(rename = "fullName", skip_serializing_if = "Option::is_none")]
        full_name: Option<String>,
        #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
        email: Option<String>,
        #[serde(rename = "ringId", skip_serializing_if = "Option::is_none")]
        ring_id: Option<String>,
        #[serde(rename = "guest", skip_serializing_if = "Option::is_none")]
        guest: Option<bool>,
        #[serde(rename = "online", skip_serializing_if = "Option::is_none")]
        online: Option<bool>,
        #[serde(rename = "banned", skip_serializing_if = "Option::is_none")]
        banned: Option<bool>,
        #[serde(rename = "isAnonymized", skip_serializing_if = "Option::is_none")]
        is_anonymized: Option<bool>,
        #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
        tags: Option<Vec<models::Tag>>,
        #[serde(rename = "savedQueries", skip_serializing_if = "Option::is_none")]
        saved_queries: Option<Vec<models::SavedQuery>>,
        #[serde(rename = "avatarUrl", skip_serializing_if = "Option::is_none")]
        avatar_url: Option<String>,
        #[serde(rename = "profiles", skip_serializing_if = "Option::is_none")]
        profiles: Option<Box<models::UserProfiles>>,
        #[serde(rename = "userType", skip_serializing_if = "Option::is_none")]
        user_type: Option<Box<models::UserType>>,
    },
    #[serde(rename="User")]
    User {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "login", skip_serializing_if = "Option::is_none")]
        login: Option<String>,
        #[serde(rename = "fullName", skip_serializing_if = "Option::is_none")]
        full_name: Option<String>,
        #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
        email: Option<String>,
        #[serde(rename = "ringId", skip_serializing_if = "Option::is_none")]
        ring_id: Option<String>,
        #[serde(rename = "guest", skip_serializing_if = "Option::is_none")]
        guest: Option<bool>,
        #[serde(rename = "online", skip_serializing_if = "Option::is_none")]
        online: Option<bool>,
        #[serde(rename = "banned", skip_serializing_if = "Option::is_none")]
        banned: Option<bool>,
        #[serde(rename = "isAnonymized", skip_serializing_if = "Option::is_none")]
        is_anonymized: Option<bool>,
        #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
        tags: Option<Vec<models::Tag>>,
        #[serde(rename = "savedQueries", skip_serializing_if = "Option::is_none")]
        saved_queries: Option<Vec<models::SavedQuery>>,
        #[serde(rename = "avatarUrl", skip_serializing_if = "Option::is_none")]
        avatar_url: Option<String>,
        #[serde(rename = "profiles", skip_serializing_if = "Option::is_none")]
        profiles: Option<Box<models::UserProfiles>>,
        #[serde(rename = "userType", skip_serializing_if = "Option::is_none")]
        user_type: Option<Box<models::UserType>>,
    },
    #[serde(rename="VcsUnresolvedUser")]
    VcsUnresolvedUser {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "login", skip_serializing_if = "Option::is_none")]
        login: Option<String>,
        #[serde(rename = "fullName", skip_serializing_if = "Option::is_none")]
        full_name: Option<String>,
        #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
        email: Option<String>,
        #[serde(rename = "ringId", skip_serializing_if = "Option::is_none")]
        ring_id: Option<String>,
        #[serde(rename = "guest", skip_serializing_if = "Option::is_none")]
        guest: Option<bool>,
        #[serde(rename = "online", skip_serializing_if = "Option::is_none")]
        online: Option<bool>,
        #[serde(rename = "banned", skip_serializing_if = "Option::is_none")]
        banned: Option<bool>,
        #[serde(rename = "isAnonymized", skip_serializing_if = "Option::is_none")]
        is_anonymized: Option<bool>,
        #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
        tags: Option<Vec<models::Tag>>,
        #[serde(rename = "savedQueries", skip_serializing_if = "Option::is_none")]
        saved_queries: Option<Vec<models::SavedQuery>>,
        #[serde(rename = "avatarUrl", skip_serializing_if = "Option::is_none")]
        avatar_url: Option<String>,
        #[serde(rename = "profiles", skip_serializing_if = "Option::is_none")]
        profiles: Option<Box<models::UserProfiles>>,
        #[serde(rename = "userType", skip_serializing_if = "Option::is_none")]
        user_type: Option<Box<models::UserType>>,
    },
}

impl Default for User {
    fn default() -> Self {
        Self::Me {
            id: Default::default(),
            login: Default::default(),
            full_name: Default::default(),
            email: Default::default(),
            ring_id: Default::default(),
            guest: Default::default(),
            online: Default::default(),
            banned: Default::default(),
            is_anonymized: Default::default(),
            tags: Default::default(),
            saved_queries: Default::default(),
            avatar_url: Default::default(),
            profiles: Default::default(),
            user_type: Default::default(),
        }
        
    }
}


