/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserCustomFieldDefaults : Represents default settings for the user-type field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCustomFieldDefaults {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "canBeEmpty", skip_serializing_if = "Option::is_none")]
    pub can_be_empty: Option<bool>,
    #[serde(rename = "emptyFieldText", skip_serializing_if = "Option::is_none")]
    pub empty_field_text: Option<String>,
    #[serde(rename = "isPublic", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Box<models::CustomField>>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "bundle", skip_serializing_if = "Option::is_none")]
    pub bundle: Option<Box<models::UserBundle>>,
    #[serde(rename = "defaultValues", skip_serializing_if = "Option::is_none")]
    pub default_values: Option<Vec<models::User>>,
}

impl UserCustomFieldDefaults {
    /// Represents default settings for the user-type field.
    pub fn new() -> UserCustomFieldDefaults {
        UserCustomFieldDefaults {
            id: None,
            can_be_empty: None,
            empty_field_text: None,
            is_public: None,
            parent: None,
            dollar_type: None,
            bundle: None,
            default_values: None,
        }
    }
}

