/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserBundle :
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserBundle {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "isUpdateable", skip_serializing_if = "Option::is_none")]
    pub is_updateable: Option<bool>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<models::UserGroup>>,
    #[serde(rename = "individuals", skip_serializing_if = "Option::is_none")]
    pub individuals: Option<Vec<models::User>>,
    #[serde(rename = "aggregatedUsers", skip_serializing_if = "Option::is_none")]
    pub aggregated_users: Option<Vec<models::User>>,
}

impl UserBundle {
    ///
    pub fn new() -> UserBundle {
        UserBundle {
            id: None,
            is_updateable: None,
            dollar_type: None,
            groups: None,
            individuals: None,
            aggregated_users: None,
        }
    }
}
