/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VcsServer : The basic entity that represents a VCS or a build server.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum VcsServer {
    #[serde(rename = "BitBucketServer")]
    BitBucketServer {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "BitbucketStandaloneServer")]
    BitbucketStandaloneServer {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "GitHubServer")]
    GitHubServer {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "GitLabServer")]
    GitLabServer {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "GiteaServer")]
    GiteaServer {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "GogsServer")]
    GogsServer {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "JenkinsServer")]
    JenkinsServer {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "SpaceServer")]
    SpaceServer {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "TeamcityServer")]
    TeamcityServer {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "VcsHostingServer")]
    VcsHostingServer {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
    #[serde(rename = "VcsServer")]
    VcsServer {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
        url: Option<String>,
    },
}

impl Default for VcsServer {
    fn default() -> Self {
        Self::BitBucketServer {
            id: Default::default(),
            url: Default::default(),
        }
    }
}
