/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VersionBundle :
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionBundle {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "isUpdateable", skip_serializing_if = "Option::is_none")]
    pub is_updateable: Option<bool>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<models::VersionBundleElement>>,
}

impl VersionBundle {
    ///
    pub fn new() -> VersionBundle {
        VersionBundle {
            id: None,
            is_updateable: None,
            dollar_type: None,
            values: None,
        }
    }
}
