/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Visibility : Represents visibility settings of an entity, for example, an issue or a comment.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "$type")]
pub enum Visibility {
    #[serde(rename="LimitedVisibility")]
    LimitedVisibility {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
    #[serde(rename="UnlimitedVisibility")]
    UnlimitedVisibility {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
    #[serde(rename="Visibility")]
    Visibility {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
    },
}

impl Default for Visibility {
    fn default() -> Self {
        Self::LimitedVisibility {
            id: Default::default(),
        }
        
    }
}


