/*
 * YouTrack REST API
 *
 * YouTrack issue tracking and project management system
 *
 * The version of the OpenAPI document: 2026.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkItemTypeActivityItem : Represents a change in the `type` attribute of the work item.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkItemTypeActivityItem {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
    pub added: Option<Vec<models::WorkItemType>>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<Box<models::User>>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<Box<models::ActivityCategory>>,
    #[serde(rename = "field", skip_serializing_if = "Option::is_none")]
    pub field: Option<Box<models::FilterField>>,
    #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
    pub removed: Option<Vec<models::WorkItemType>>,
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<Box<models::IssueWorkItem>>,
    #[serde(rename = "targetMember", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub target_member: Option<Option<String>>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(rename = "$type", skip_serializing_if = "Option::is_none")]
    pub dollar_type: Option<String>,
}

impl WorkItemTypeActivityItem {
    /// Represents a change in the `type` attribute of the work item.
    pub fn new() -> WorkItemTypeActivityItem {
        WorkItemTypeActivityItem {
            id: None,
            added: None,
            author: None,
            category: None,
            field: None,
            removed: None,
            target: None,
            target_member: None,
            timestamp: None,
            dollar_type: None,
        }
    }
}

